# .github/workflows/main.yml

name: CI/CD Pipeline - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: qr-code-generator-app
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇️ Checkout Repository
      uses: actions/checkout@v4

    - name: 🔑 Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 📐 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔨 Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

    - name: ✅ Run a basic container test
  # Temporarily remove '--rm' to allow logs to be captured before manual cleanup
      run: |
        # 1. Start the container in detached mode (without --rm)
        docker run -d --name test-run ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        
        # 2. Wait for the application to finish its task (5 seconds is usually enough)
        sleep 5 
        
        # 3. Print the logs (this will succeed now as the container still exists, though it has exited)
        docker logs test-run
        
        # 4. Cleanup: Stop and remove the container
        docker stop test-run
        docker rm test-run
      shell: /usr/bin/bash -e {0}